FROM node:18-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

RUN pnpm add -g chopd

COPY chopin.config.json ./

# Ortam değişkenleri Dockerfile'dan kaldırıldı ve docker-compose'a taşındı
CMD ["sh", "-c", "chopd $PROXY_PORT $TARGET_PORT"] 