---
version: "3"

volumes:
  postgres:

services:
  postgres:
    command: postgres -c max_connections=200 -c listen_addresses='*'
    environment:
      POSTGRES_USER: xora
      POSTGRES_DATABASE: xora
      POSTGRES_PASSWORD: xora
    image: postgres:16-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
