version: "3.9"

services:
  nginx:
    extends:
      file: docker-compose.base.yml
      service: nginx
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

  nextjs:
    extends:
      file: docker-compose.base.yml
      service: nextjs
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "4000:4000"
      - "3000:3000"

  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres
    ports:
      - "5432:5432"

volumes:
  node_modules:
  postgres_data:

networks:
  app_network:
    driver: bridge 