name: Deploy

on:
  push:
    branches:
      - main 
  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and deploy
        run: |
          export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          export POSTGRES_DATABASE=${{ secrets.POSTGRES_DATABASE }}
          export DATABASE_URL=${{ secrets.DATABASE_URL }}
          export DOMAIN=${{ secrets.DOMAIN }}
          export NODE_ENV=production

          chmod +x scripts/nginx-entrypoint.sh
          
          docker compose -f docker-compose.prod.yml build
          docker compose -f docker-compose.prod.yml down
          docker compose -f docker-compose.prod.yml up -d